### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by Frodwo** [SlimeTraditionalTranslation/Slimefun4#12]
[https://pastebin.com/Nui6wNzk](https://pastebin.com/Nui6wNzk)
Error Generated: 2022-07-18-10-10

Java Environment:
  Operating System: Linux
  Java Version: 17.0.3

Server Software: Paper
  Build: git-Paper-216 (MC: 1.18.1)
  Minecraft v1.18.1-R0.1-SNAPSHOT

Slimefun Environment:
  Slimefun vTEA - 235 (git d2aad1ea)
  Caused by: InfinityExpansion vEFI - 58 (git ec6764d4)

Installed Addons (27)
  + EcoPower EFI - 8 (git b2c300d3)
  + ExoticGarden WEI - 26 (git 47f7881a)
  + Liquid EFI - 12 (git 077c155f)
  + LiteXpansion EFI - 65 (git dae48d13)
  + SoulJars EFI - 8 (git 728d6b86)
  + ExtraTools EFI - 11 (git 8642222f)
  + RelicsOfCthonia EFI - 4 (git 64f8f10d)
  + SlimefunOreChunks EFI - 9 (git 0516d90e)
  + PrivateStorage EFI - 7 (git da8822d4)
  + Galactifun EFI - 46 (git 243a4494)
  + MissileWarfare 1.5.1
  + SimpleStorage EFI - 9 (git e91cbb69)
  + ShopGUIPlus 1.76.0
  + SfChunkInfo EFI - 2 (git 454b3aea)
  + MobCapturer EFI - 9 (git a85d1964)
  + HotbarPets EFI - 9 (git 9a083742)
  + WipeGhostSlimefunBlock 1.0-SNAPSHOT
  + ElectricSpawners EFI - 7 (git 31f13173)
  + FlowerPower EFI - 13 (git dda6c260)
  + FluffyMachines EFI - 85 (git 48b4f913)
  + DyedBackpacks EFI - 10 (git 0cd1aa5b)
  + SoundMuffler EFI - 10 (git 368a6184)
  + CrystamaeHistoria EFI - 9 (git 11ebcec9)
  + InfinityExpansion EFI - 58 (git ec6764d4)
  + Networks EFI - 25 (git 9c40520a)
  + DynaTech EFI - 102 (git 68503877)
  + SimpleUtils EFI - 13 (git ae0d65d8)

Block Info:
  World: SuperiorWorld_nether
  X: -6608
  Y: 150
  Z: 11377
  Material: FURNACE
  Block Data: org.bukkit.craftbukkit.v1_18_R1.block.impl.CraftFurnaceFurace
  State: org.bukkit.craftbukkit.v1_18_R1.block.CraftFurnaceFurnace

Ticker-Info:
  Type: Asynchronous

Slimefun Data:
  ID: INFINITY_QUARRY
  Inventory: true
  Data: {"energy-charge":"72000","id":"INFINITY_QUARRY"}

Stacktrace:

java.lang.ArrayIndexOutOfBoundsException

**Comment by xMikux** [comment]
我剛進行了測試 並未看到方塊消失的問題
不太確定原因, 且裡面包含了一個我沒看過的附加
WipeGhostSlimefunBlock

**Comment by xMikux** [comment]
有他如何觸發的條件嘛

**Comment by xMikux** [comment]
由於無任何後續回覆，此問題將會被關閉。
